#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap           7
bspc config focused_border_color "#04dcb3"
bspc config normal_border_color  "#707070"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 10


#AutoStart apps

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
flameshoot &
xsetroot -cursor_name left_ptr &
/home/starplatinum/.scripts/set_default_sinks.sh & #script to set default audio and input devices
/home/starplatinum/.scripts/start_apps/start-all.sh &
